[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm ci --legacy-peer-deps --prefix frontend"]

[phases.build]
cmds = ["CI=false npm run build --prefix frontend"]

[start]
cmd = "npx serve -s frontend/build -l $PORT"
